import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { Layout } from "antd";
import { ConfigProvider } from "antd";
import { Provider } from "@/utils/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <QueryClientProvider client={queryClient}> */}
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
      {/* </QueryClientProvider> */}
    </html>
  );
}
